stages:
  - build

job1:
  stage: build
  only:
    - master
  script:
    - curl 'https://www.kernel.org/pub/linux/utils/boot/syslinux/6.xx/syslinux-6.03.zip' > deps/syslinux.zip
    - make all images
  artifacts:
    name: "%CI_BUILD_REF_NAME"
    paths:
      - phoenixos
      - phoenixos.iso
