stages:
  - build
  - docs

build:
  stage: build
  cache:
    paths:
      - deps
  script:
    - make images
  artifacts:
    name: "$CI_BUILD_REF_NAME"
    paths:
      - bin

pages:
  stage: docs
  environment:
    name: production
    url: https://os.phoenix.dj
  script:
    - mkdocs build
  artifacts:
    paths:
      - public
    expire_in: 1h
  only:
    - master@phoenix/phoenix-os
