stages:
  - build
  - docs

build:
  stage: build
  cache:
    paths:
      - build/*-prefix
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make all iso VERBOSE=1
  artifacts:
    name: "$CI_BUILD_REF_NAME"
    paths:
      - build/pxkrnl
      - build/phoenixos.iso

pages:
  stage: docs
  environment:
    name: production
    url: https://os.phoenix.dj
  script:
    - mkdocs build
  artifacts:
    paths:
      - public
    expire_in: 1h
  only:
    - master@phoenix/phoenix-os
